import type { Metadata } from 'next'

const SITE = 'Cipher Text Lab'
// Generated by app/opengraph-image.tsx. Set explicitly because a page-level openGraph replaces the file-based one.
const OG_IMAGE = { url: '/opengraph-image', width: 1200, height: 630, alt: 'Cipher Text Lab' }

/**
 * Page metadata with matching Open Graph / Twitter text.
 * Next replaces (not merges) openGraph per page, so each page sets its own.
 * Pass `absolute` for a title that should skip the "| Cipher Text Lab" template.
 */
export function pageMetadata({ title, description, absolute = false }: { title: string; description: string; absolute?: boolean }): Metadata {
  const full = absolute ? title : `${title} | ${SITE}`
  return {
    title: absolute ? { absolute: title } : title,
    description,
    openGraph: { title: full, description, siteName: SITE, type: 'website', locale: 'en_US', images: [OG_IMAGE] },
    twitter: { card: 'summary_large_image', title: full, description, images: [OG_IMAGE.url] },
  }
}
